spring.application.name=learningmvcarchitectureofspringboot
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:./data/db
spring.datasource.username=rahul
spring.datasource.password=rahul123
spring.jpa.hibernate.ddl-auto=update


